typography_spectrum: 0.3284706575796008
color:
  brandStrength: 0.1846688233781606
  lightness: 0.543801296968013
  saturation: 0.6336268773302436
  rhythmicContrast: 0.3401187949348241
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.1394538446329534
name: 'The Bold and the Digital '
title: The Bold and the Digital
description: 'Your A.I Powered Digital blog - powered by A.I Responsive Design '
