typography_spectrum: 0.2981728157028556
color:
  brandStrength: 0.1592592322267592
  lightness: 0.5521559433545917
  saturation: 0.3901932917069644
  rhythmicContrast: 0.1422887220978737
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.5496087376959622
name: 'The Bold and the Digital '
navigation:
  - name: 33 Women Doing Amazing Things in Graphic Design
    id: 8b17758b-8c70-4630-a713-24b2accb19e0
    type: content
title: The Bold and the Digital
description: 'Your A.I Powered Digital blog - powered by A.I Responsive Design '
